name: build-merge

on:
  push:
    branches: master
    paths:
      - ".github/actions/merge/*"
      - .github/workflows/merge.yml
      - .github/workflows/build-merge.yml
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
        with:
          persist-credentials: false

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # v3

      - name: Login to ghcr.io
        uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@ca052bb54ab0790a636c9b5f226502c73d547a25 # v5
        with:
          context: .github/actions/merge
          file: .github/actions/merge/Dockerfile
          tags: ghcr.io/flathub/actions/merge:latest
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
